v0.07w7

diff --git a/install b/install
--- a/install
+++ b/install
@@ -38,11 +38,13 @@ if [ $? -ne 0 ]; then
 	exit 1;
 fi
 
-ldconfig
+if [ -e `which ldconfig`]; then
+	ldconfig
 
-if [ $? -ne 0 ]; then
-	echo "Failed to execute ldconfig"
-	exit 1;
+	if [ $? -ne 0 ]; then
+		echo "Failed to execute ldconfig"
+		exit 1;
+	fi
 fi
 
 echo "Installation complete."
