v0.08a5

diff --git a/uconf/bin/undo b/uconf/bin/undo
--- a/uconf/bin/undo
+++ b/uconf/bin/undo
@@ -4,7 +4,7 @@
 #
 # Copyright 2014-2015 Pedro A. Hortas (pah@ucodev.org)
 #
-# Date: 16/03/2015
+# Date: 23/03/2015
 #
 # URL: http://www.ucodev.org
 #
@@ -30,6 +30,8 @@ if [ `id -u` -ne 0 ]; then
 	exit 1
 fi
 
+. ./uconf/lib/sh/varundo.inc
+
 if [ -e ./uconf/params/default/undo ]; then
 	while read cmd; do
 		/bin/sh -c "${cmd}"
@@ -52,6 +54,19 @@ if [ -e ./uconf/params/`cat .osname 2> /dev/null`/undo ]; then
 	done < ./uconf/params/`cat .osname`/undo
 fi
 
+if [ -e ./uconf/params/user/undo ]; then
+	while read cmd; do
+		/bin/sh -c "${cmd}"
+
+		if [ $? -ne 0 ]; then
+			echo "Failed to execute: ${cmd}"
+			exit 1
+		fi
+	done < ./uconf/params/user/undo
+fi
+
+rm -rf ./uconf/params/user
+
 rm -rf build
 rm -f .target
 rm -f .osname
@@ -64,4 +79,5 @@ rm -f .archflags
 rm -f .addons
 rm -f .done
 rm -f .l*
+rm -f .dir*
 
